project:
  type: website

website:
  title: "Embedded RTOS Course eBook"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Modules"
        menu:
          - text: "Module 1: Processes Intro"
            href: lecture01.qmd
          - text: "Module 1 Slides"
            href: module01/slides.qmd
          - text: "Module 2: Anatomy of Linux Systems"
            href: lecture02.qmd
          - text: "Module 2 Slides"
            href: module02/slides.qmd
          - text: "Module 3: Processes and OS Management"
            href: module03.qmd
          - text: "Module 3 Slides"
            href: Module03_slidedeck.qmd
  sidebar:
    style: floating
    search: true
    collapse-level: 2
    contents:
      - index.qmd
      - section: "Module 1: Processes Intro"
        contents:
          - lecture01.qmd
          - module01/slides.qmd
      - section: "Module 2: Anatomy of Linux Systems"
        contents:
          - lecture02.qmd
          - module02/slides.qmd
      - section: "Module 3: Processes and OS Management"
        contents:
          - lecture03.qmd
          - Module03_slidedeck.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
  revealjs:
    theme: simple
    slide-number: true
    chalkboard: true
    transition: fade
    center: true
